@startuml duress_protection_withdrawal_diagram
skinparam sequenceMessageAlign left
title Duress Protection Withdrawal Sequence Diagram
box "User Side" #AliceBlue
actor User order 1 #LightCyan
participant Iso order 2 #LightBlue
participant Boomlet order 3 #LightPink
participant ST order 4 #Violet
participant Niso order 5 #LightGreen
end box
participant WTs order 98 #Red
participant SARs order 99 #Yellow
actor Peers order 100


autonumber "<b>Message 00:"

autonumber stop
User <-> Iso: keeping                       the                              social                            \n distance
Iso <-> Boomlet: keeping                       the                              social                         \n distance
Boomlet <-> ST: keeping                       the                              social                          \n distance
ST <-> Niso: keeping                       the                              social                             \n distance
Niso <-> WTs: keeping                       the                              social                            \n distance
WTs <-> SARs: keeping                       the                              social                            \n distance
SARs <-> Peers: keeping                       the                              social                          \n distance
autonumber resume

' Initiation
note over Boomlet: **Boomlet** \n [...] \n boomlet_0_identity_privkey \n boomlet_0_identity_pubkey \n st_0_identity_pubkey \n shared_boomlet_st_privkey \n duress_consent_set
/ note over ST: **ST** \n boomlet_0_identity_pubkey \n st_0_identity_privkey \n st_0_identity_pubkey \n shared_boomlet_st_privkey
/note over Iso: **Iso** \n
/ note over User: **User** \n name_of_5_consent_countries_in_brain_memory

hnote over Boomlet #Red: DURESS CHECK INITIATED VIA BOOMLET
hnote over Boomlet: Boomlet will create 5 randomly ordered set of numbers \n between 1 and 195 inclusive and encrypt the container collection with \n its shared key with ST: \n temp_duress_message_collection:=[rand_order[1..195]; 5] \n _duress_message_collection_encrypted_by_boomlet_for_st:=AES_encrypt(shared_boomlet_st_privkey, \n temp_duress_message_collection)
note over Boomlet: **Boomlet** \n [...] \n boomlet_0_identity_privkey \n boomlet_0_identity_pubkey \n st_0_identity_pubkey \n shared_boomlet_st_privkey \n duress_consent_set \n --Duress Check-- \n <i>temp_duress_message_collection \n <i>_duress_message_collection_encrypted_by_boomlet_for_st

' Step 1
Boomlet -> Niso: duress_message_collection_encrypted_by_boomlet_for_st
hnote over Niso: Niso will encode the received encrypted message to a QR code \n and will display it on its monitor for ST to scan.
note over Niso: **Niso** \n [...] \n --Duress Check-- \n <i>_duress_message_collection_encrypted_by_boomlet_for_st

' Step 2
Niso o-> ST: **QR**(duress_message_collection_encrypted_by_boomlet_for_st)
hnote over ST: ST will decrypt the received message: \n duress_message_collection:=AES_decrypt(shared_boomlet_st_privkey, \n duress_message_collection_encrypted_by_boomlet_for_st)
note over ST: **ST** \n boomlet_0_identity_pubkey \n st_0_identity_privkey \n st_0_identity_pubkey \n shared_boomlet_st_privkey \n --Duress Check-- \n <i>_duress_message_collection
hnote over ST: ST will assign a country to each of the 5 sets retrieved \n after decryption in the previous manner and show 5 columns \n to the user on its monitor.

' Step 3
ST o-> User: **Monitor**(duress_message_collection)
hnote over User: User will select 1 country from each column shown on the ST \n to signal their duress situation
note over User: **User** \n name_of_5_consent_countries_in_brain_memory \n <i>_duress_message_collection_index_collection

' Step 4
User o-> ST: **ST's Joystick**(duress_message_collection_index_collection)
note over ST: **ST** \n boomlet_0_identity_pubkey \n st_0_identity_privkey \n st_0_identity_pubkey \n shared_boomlet_st_privkey \n --Duress Check-- \n <i>_duress_message_collection_index_collection
hnote over ST: ST will encrypt `duress_message_collection_index_collection` \n with `shared_boomlet_st_privkey`: \n duress_message_collection_index_collection_encrypted_by_st_for_boomlet:=AES_encrypt(shared_boomlet_st_privkey, \n duress_message_collection_index_collection)
note over ST: **ST** \n boomlet_0_identity_pubkey \n st_0_identity_privkey \n st_0_identity_pubkey \n shared_boomlet_st_privkey \n --Duress Check-- \n <i>_duress_message_collection_index_collection_encrypted_by_st_for_boomlet

' Step 5
ST o-> Niso: **QR**(duress_message_collection_index_collection_encrypted_by_st_for_boomlet)
note over Niso: **Niso** \n [...] \n --Duress Check-- \n <i>_duress_message_collection_index_collection_encrypted_by_st_for_boomlet

' Step 6
Niso o-> Boomlet: duress_message_collection_index_collection_encrypted_by_st_for_boomlet
hnote over Boomlet: Boomlet will decrypt the received message: \n duress_message_collection_index_collection:=AES_decrypt(shared_boomlet_st_privkey, \n duress_message_collection_index_collection_encrypted_by_st_for_boomlet)
note over Boomlet: **Boomlet** \n [...] \n boomlet_0_identity_privkey \n boomlet_0_identity_pubkey \n st_0_identity_pubkey \n shared_boomlet_st_privkey \n duress_consent_set \n --Duress Check-- \n temp_duress_message_collection \n <i>_duress_message_collection_index_collection
hnote over Boomlet: Boomlet will search for the indices in `temp_duress_message_collection` and \n if the resulting 5 numbers corresponding to the aforementioned indices, constitute \n the same set as the `duress_consent_set`, boomlet knows that the user is not in duress. \n Otherwise the user is in duress.
hnote over Boomlet: Boomlet will drop redundant data and indicate user's duress situation in \n a variable based on the latest evaluation: \n user_is_in_duress:=bool
note over Boomlet: **Boomlet** \n [...] \n boomlet_0_identity_privkey \n boomlet_0_identity_pubkey \n st_0_identity_pubkey \n shared_boomlet_st_privkey \n duress_consent_set \n --Duress Check-- \n <i>user_is_in_duress
hnote over Boomlet: Boomlet in any duress check instance will need to send another message \n in withdrawal procedure. Lets name it **Withdrawal Message**
hnote over Boomlet: Boomlet will create its usual WithdrawalMessage. Each WithdrawalMessage \n has a `duress_bearing_payload`: \n WithdrawalMessage:=[...]+duress_bearing_payload \n In case of duress, boomlet will fill the `duress_bearing_payload` with the doxing_password \n encrypted by the shared key between itself and the SAR. Otherwise, a random data with \n equal length to 'doxing_password' will be replaced with it. \n Here we need something from setup, so we show them in the state.
note over Boomlet: **Boomlet** \n [...] \n shared_boomlet_sar_privkey \n doxing_password \n [...] \n boomlet_0_identity_privkey \n boomlet_0_identity_pubkey \n st_0_identity_pubkey \n shared_boomlet_st_privkey \n duress_consent_set \n --Duress Check-- \n <i>user_is_in_duress



group User In Duress [user_in_duress = true]
hnote over Boomlet: encrypted_duress_payload := AES_encrypt(shared_boomlet_sar_privkey, duress_key)
hnote over Boomlet: WithdrawalMessage 01 := [...] + encrypted_duress_payload
end

group User Not In Duress [user_in_duress = false]
hnote over Boomlet: encrypted_duress_payload := AES_encrypt(shared_boomlet_sar_privkey, [0; 32])
hnote over Boomlet: WithdrawalMessage 01 := [...] + encrypted_duress_payload
end

autonumber "<b>WithdrawalMessage 00:"
Boomlet -> Niso: [...] + encrypted_duress_payload
note over Niso: **Niso** \n [...] \n --Duress Check-- \n <i>withdrawal_message_01

' Step 7
autonumber 7 "<b>Message [00]:"
Niso o-> WTs: withdrawal_message_01
hnote over WTs: WT will decompose the message into two parts. The first is the usual withdrawal \n part and the second is the `encrypted_duress_payload`. \n WT will send the `encrypted_duress_payload` to the pertinent SARs.\

' Step 8
WTs o-> SARs: encrypted_duress_payload
note over SARs: **SAR** \n [...] \n shared_boomlet_sar_privkey \n [...] \n --Duress Check-- \n <i>encrypted_duress_payload
hnote over SARs: SAR will decrypt the duress payload received. \n duress_payload := AES_decrypt(shared_boomlet_sar_privkey, encrypted_duress_payload)
note over SARs: **SAR** \n [...] \n shared_boomlet_sar_privkey \n [...] \n --Duress Check-- \n encrypted_duress_payload \n <i>duress_payload
hnote over SARs: SAR will check the now decrypted duress_payload. \n If it's all zeros we are not in duress. \n If it's not all zeros, SAR will hash it to get the identifier. \n doxing_identifier := SHA256(duress_payload) \n SAR will search for the same identifier in its database. If found, the user is in duress. \n If not, the message is malformed and SAR will act accordingly.

group User Not In Duress [duress_payload is all zeroes]
hnote over SARs: SAR does nothing regarding the search and rescue operation.
end

group User In Duress [doxing_identifier is found in database]
hnote over SARs: The `doxing_key` will be used to decrypt dynamic and static doxing data and the search \n and rescue operation will start. If a match is not found, the message will be deemed as malformed.
end

group Malformed Message [doxing_identifier is not found in database]
hnote over SARs: SAR detects that something is wrong, either in Niso or in WT. \n The SAR will keep a counter of this event and should it reach \n a predefined limit, will deem the setup malfunctioning \n and stop responding to halt the procedure.
end

hnote over SARs: SAR will sign the received message, drop the redundant data and send the signed message to \n the WT. \n duress_payload_signed_by_sar := Sign(sar_identity_privkey, encrypted_duress_payload)

' Step 9
SARs o-> WTs: duress_payload_signed_by_sar

hnote over WTs #Red: WT will include this signature in its reply to the participants \n and boomlet will check the inclusion and soundness of this \n payload to further the protocol.

note over Boomlet: **Boomlet** \n [...] \n shared_boomlet_sar_privkey \n doxing_password \n [..sar_identity_pubkey...] \n [...] \n boomlet_0_identity_privkey \n boomlet_0_identity_pubkey \n st_0_identity_pubkey \n shared_boomlet_st_privkey \n duress_consent_set \n --Duress Check-- \n user_is_in_duress
/note over ST: **ST** \n boomlet_0_identity_pubkey \n st_0_identity_privkey \n st_0_identity_pubkey \n shared_boomlet_st_privkey
/note over Niso:**Niso** \n [...]
/note over WTs: **WT** \n [...]
/note over Iso: **Iso** \n [...]
/note over User: **User** \n [...] \n name_of_5_consent_countries_in_brain_memory
/note over SARs: **SAR** \n [...] \n shared_boomlet_sar_privkey \n [...]

hnote over Boomlet: When one duress check is positive, all messages afterwards bear the duress signal, \n regardless of user's input to the duress check.
@enduml
